BUG: Cython 0.22 compat
We got this error when updating:

------------------------------------------------------------
/home/jorge/anaconda/bin/pip run on Thu Mar  5 09:59:27 2015
Obtaining file:///home/jorge/code/forks/biom-format
  Running setup.py (path:/home/jorge/code/forks/biom-format/setup.py) egg_info for package from file:///home/jorge/code/forks/biom-format
    
    Error compiling Cython file:
    ------------------------------------------------------------
    ...
                offset += end - start
                offset_rows += 1
        arr.data = data[:nnz]
        arr.indices = indices[:nnz]
        arr.indptr = indptr[:m-offset_rows+1]
        arr._shape = (m - offset_rows, n) if m-offset_rows else (0, 0)
                    ^
    ------------------------------------------------------------
    
    biom/_filter.pyx:87:17: Incompatible types in conditional expression ((Py_ssize_t, Py_ssize_t); (long, long))
    Compiling biom/_filter.pyx because it depends on /home/jorge/anaconda/lib/python2.7/site-packages/Cython/Includes/numpy/__init__.pxd.
    Compiling biom/_transform.pyx because it depends on /home/jorge/anaconda/lib/python2.7/site-packages/Cython/Includes/numpy/__init__.pxd.
    Compiling biom/_subsample.pyx because it depends on /home/jorge/anaconda/lib/python2.7/site-packages/Cython/Includes/numpy/__init__.pxd.
    Cythonizing biom/_filter.pyx
    Traceback (most recent call last):
      File "<string>", line 17, in <module>
      File "/home/jorge/code/forks/biom-format/setup.py", line 80, in <module>
        extensions = cythonize(extensions)
      File "/home/jorge/anaconda/lib/python2.7/site-packages/Cython/Build/Dependencies.py", line 865, in cythonize
        cythonize_one(*args[1:])
      File "/home/jorge/anaconda/lib/python2.7/site-packages/Cython/Build/Dependencies.py", line 985, in cythonize_one
        raise CompileError(None, pyx_file)
    Cython.Compiler.Errors.CompileError: biom/_filter.pyx
    Complete output from command python setup.py egg_info:
    

Error compiling Cython file:

------------------------------------------------------------

...

            offset += end - start

            offset_rows += 1

    arr.data = data[:nnz]

    arr.indices = indices[:nnz]

    arr.indptr = indptr[:m-offset_rows+1]

    arr._shape = (m - offset_rows, n) if m-offset_rows else (0, 0)

                ^

------------------------------------------------------------



biom/_filter.pyx:87:17: Incompatible types in conditional expression ((Py_ssize_t, Py_ssize_t); (long, long))

Compiling biom/_filter.pyx because it depends on /home/jorge/anaconda/lib/python2.7/site-packages/Cython/Includes/numpy/__init__.pxd.

Compiling biom/_transform.pyx because it depends on /home/jorge/anaconda/lib/python2.7/site-packages/Cython/Includes/numpy/__init__.pxd.

Compiling biom/_subsample.pyx because it depends on /home/jorge/anaconda/lib/python2.7/site-packages/Cython/Includes/numpy/__init__.pxd.

Cythonizing biom/_filter.pyx

Traceback (most recent call last):

  File "<string>", line 17, in <module>

  File "/home/jorge/code/forks/biom-format/setup.py", line 80, in <module>

    extensions = cythonize(extensions)

  File "/home/jorge/anaconda/lib/python2.7/site-packages/Cython/Build/Dependencies.py", line 865, in cythonize

    cythonize_one(*args[1:])

  File "/home/jorge/anaconda/lib/python2.7/site-packages/Cython/Build/Dependencies.py", line 985, in cythonize_one

    raise CompileError(None, pyx_file)

Cython.Compiler.Errors.CompileError: biom/_filter.pyx

----------------------------------------
Cleaning up...
  Removing temporary dir /tmp/pip_build_jorge...
Command python setup.py egg_info failed with error code 1 in /home/jorge/code/forks/biom-format
Exception information:
Traceback (most recent call last):
  File "/home/jorge/anaconda/lib/python2.7/site-packages/pip/basecommand.py", line 122, in main
    status = self.run(options, args)
  File "/home/jorge/anaconda/lib/python2.7/site-packages/pip/commands/install.py", line 278, in run
    requirement_set.prepare_files(finder, force_root_egg_info=self.bundle, bundle=self.bundle)
  File "/home/jorge/anaconda/lib/python2.7/site-packages/pip/req.py", line 1145, in prepare_files
    req_to_install.run_egg_info()
  File "/home/jorge/anaconda/lib/python2.7/site-packages/pip/req.py", line 325, in run_egg_info
    command_desc='python setup.py egg_info')
  File "/home/jorge/anaconda/lib/python2.7/site-packages/pip/util.py", line 697, in call_subprocess
    % (command_desc, proc.returncode, cwd))
InstallationError: Command python setup.py egg_info failed with error code 1 in /home/jorge/code/forks/biom-format